syncer:
  ack:
    flushPeriod: 100
  input:
    worker: 4
    max-retry: 5
    input-meta:
      last-run-metadata-dir: /data/syncer/input/last_position/

  filter:
    worker: 6

  output:
    worker: 2
    batch:
      worker: 2
    output-meta:
      failure-log-dir: /data/syncer/output/failure/
